# Generated by Django 5.2 on 2025-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('num_reviews', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
